// Generated by https://quicktype.io

export interface ResponseUserByHandle {
    message: string;
    user:    UserWithHandle;
}

export interface UserWithHandle {
    name:        string;
    email:       string;
    links:       string[];
    description: string;
    image:       string;
}
