import { AuthFormData } from "../../auth/interface/AuthFormData.interface";

export interface ResponseUserUpdated{
    message:     string;
    user:        AuthFormData;
}


// Generated by https://quicktype.io

export interface ResponseUserAuthenticated {
    message: string;
    user:    User;
}

export interface User {
    id:          string;
    handle:      string;
    name:        string;
    email:       string;
    createdAt:   Date;
    description: string;
    image:       string;
    links:       string[];
}
